items:
  metatag.settings:
    expected_config:
      entity_type_groups: { }
    update_actions:
      add:
        entity_type_groups:
          group:
            flexible_group:
              basic: basic
              open_graph: open_graph
          group_content:
            flexible_group-group_node-event:
              basic: basic
              open_graph: open_graph
            flexible_group-group_node-topic:
              basic: basic
              open_graph: open_graph
          node:
            event:
              basic: basic
              open_graph: open_graph
            page:
              basic: basic
              open_graph: open_graph
            topic:
              basic: basic
              open_graph: open_graph
          profile:
            profile:
              basic: basic
              open_graph: open_graph
          user:
            user:
              basic: basic
              open_graph: open_graph

