field.field.activity.activity.field_activity_entity:
  expected_config: {  }
  update_actions:
    delete:
      settings:
        group:
          handler_settings:
            target_bundles:
              open_group: open_group
    add:
      settings:
        group:
          handler_settings:
            target_bundles:
              flexible_group: flexible_group
